kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
  namespace: ghost
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: ghost
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-app
  template:
    metadata:
      labels:
        app: ghost-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: ghost-app
        image: drs-ghost:v1.5
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: "1"
            memory: 512Mi
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 2368
          name: ghost-app
        volumeMounts:
        - name: azure-managed-disk
          mountPath: /var/lib/ghost/content/
      volumes:
      - name: azure-managed-disk
        persistentVolumeClaim:
          claimName: ghost-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-app
  namespace: ghost 
spec:
  type: ClusterIP
  selector:
    app: ghost-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ghost-app-hpa
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ghost-app
  targetCPUUtilizationPercentage: 50